# Test HTTP requests
### use with: REST Client extension
@apiurl = http://localhost:3000/api

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozMCwidXNlcm5hbWUiOiJtaWthbWV0cm9wb2xpYSIsImVtYWlsIjoibWlrYXBvaUBtZXRyb3BvbGlhLmZpIiwiY3JlYXRlZF9hdCI6IjIwMjYtMDMtMDNUMDk6MzY6MDQuMDAwWiIsInVzZXJfbGV2ZWwiOiJyZWd1bGFyIiwiaWF0IjoxNzcyNjI4NzMzLCJleHAiOjE3NzI3MTUxMzN9.A8kpqEUI2kg8iv48IzdODM9Wywfm3y77yL9RBH2fUSg
GET {{apiurl}}/items

### GET item with id 1
GET {{apiurl}}/items/1

### Add new item
POST {{apiurl}}/items
Content-Type: application/json

{"name": "Mandariini", "weight": 86}

### Delete item with id 2
DELETE {{apiurl}}/items/2

### Update item with id 1
PUT {{apiurl}}/items/1
Content-Type: application/json

{"name": "updated Omena"}

##############################
### users endpoints

### Get all users (Fail without log in. Change token to muuttuja)
GET {{apiurl}}/users
Authorization: Bearer {{token}}


### Get all users (Fail without token)
GET {{apiurl}}/users


########
###Get user by id:
GET  {{apiurl}}/users/9



### Register new user
POST {{apiurl}}/users
Content-Type: application/json

{
  "username": "Mikafinal",
  "password": "testi123",
  "email": "final@final.fi"
}

### Register new user FAIL (email missing)
POST {{apiurl}}/users
Content-Type: application/json

{
  "username": "donald",
  "password": "duck"
}

### User login Tähän tehty salasanan tarkistus hashattyna. Tee tän mukaan omaan!!!!!!!!!!!
POST {{apiurl}}/users/login
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "username": "mikametropolia",
  "password": "Aquamariinioy1"
}


### GET userinfo by token
GET {{apiurl}}/users/me
Authorization: Bearer {{token}}

### Diary entry endpoints

### Get all entries (by user id tokenista)
GET {{apiurl}}/entries
Authorization: Bearer {{token}}

### Get entry by id //alempana laitetaan entry ja voi hakea viimeisimmällä tästä entrin
GET {{apiurl}}/entries/9

### Delete entry by id
DELETE {{apiurl}}/entries/8
Authorization: Bearer {{token}}




### post new entry
POST {{apiurl}}/entries
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "user_id": 23,
  "entry_date": "2026-02-05",
  "mood": "Kipeä",
  "weight": 101,
  "sleep_hours": 7,
  "notes": "testikirjaus"
}

############### oma-kanta request
GET {{apiurl}}/omakanta/stats/

###############
POST {{apiurl}}/omakanta/stats
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "user_id": 30,
  "calories_eaten": 2250,
  "entry_date": "2026-02-05",
  "calories_used": 2300,
  "steps": 7202,
  "weight_today": 99,
  "mood": "hyvä",
  "weight": 103,
  "sleep_hours": 8,
  "notes": "Vielä on flunssan jälkitilaa. Vointi ei vielä paras ja vähän yskittää"
}

############################### omakanta Get Health stats
GET {{apiurl}}/omakanta/stats/16
Authorization: Bearer {{token}}

### User login Tähän tehty salasanan tarkistus hashattyna. Tee tän mukaan omaan!!!!!!!!!!!
POST {{apiurl}}/omakanta/stats/login
Content-Type: application/json

{
  "username": "mika123",
  "password": "kissa"
}

### GET userinfo by token
GET {{apiurl}}/omakanta/stats/me
Authorization: Bearer {{token}}